language: scala

jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
    - secure: ZlMzvn7Jlxbzbd8MNsxerPVPiTXXYdRj6i+AhyYN69nmjF9Re5Y6xaViEpxqL7jXL/0qQUKtM2he7TJFxzuhxZc32N0OCQ0euCuE6krBygRZ7Re+CFKEjGp1WCnySDpcpqWeDYKAvk6OtWm5q3TW+pFwF0UT/aL7xT0wdJrN8fU=
    - secure: oi5wtujkvD+B6oUEl8xFaW7bv2KilVX+v1mxS9WH5lHH0ei0RdCPbDcUR+9wqEfMzybPfmazvgK2UFk6GfrSuIR33iSJ3+MG9UMApUlX9eSgn7QM2OfZa/sLNjTKCjDnsTpRE+59VPBGEQsRTWVm2fl/iffyRZ/ervtd+qffcy8=
    - secure: UEwEEb3YXIgwofNBaaKBuqiyTNXOAqjfvJ+zPU6lUqJsoqPfemWL4Ikb7K8bA2domIgVAiMKmPm3FCAKFeeqm2QLRt0MQmqW6RUmKWFm2/12w9m3CFvTnBpDDdk8HUleXxs1FFZdflWYecBmoJqq8djO/wz7dJbPuPZkKU1NlLM=
    - secure: IP0Y5ARS9OfOP+RNFfBR7VwzQq9QSvFIAqsvXvyyxbKw8senacCyUa/rl2+naj7tIjuDyfUQGgMLuK8espx19ccZFN6UXNGS9izVjYbd7jKPviTZ4vCpqliz4FECux0tikWYV/AfwIf8hCKihdedl18/5kzU5tGz1JJQRP6T5ps=
    - secure: JnB8wDYEB7CzeNdAdTRrhX7TWS9yM/BNQxd4rF95pTXEhPyBAaYFMgHcauWfRurlbPPwDGIsuEvLQR+eYpp9xScJilgxKT6O1IIPVoZAbd6q+i2Qj4woh+++/M7opvbBlbyCBzlyVC9CZ0xDQo7rt+pxGjNnMYHG2SftcOkjlpU=
  matrix:
    - scala: 2.11.12
      env: SCALA_MINOR=2.11
    - scala: 2.12.6
      env: SCALA_MINOR=2.12

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: checkout
      name: 'Checkout Travis and Log'
      script: git clone -b travis `git config --get remote.origin.url` target/travis
    - script: echo "Is tag build $TRAVIS_TAG"
      if: tag IS present
    - script: echo "Pull request build"
      if: type = pull_request
    - script: echo "Branch build, ${TRAVIS_BRANCH}"
      if: type = push

    - stage: version
      name: 'Set Version'
      script: mvn versions:set "-DnewVersion=${TRAVIS_TAG}" "-Dscala.artifact.version=${SCALA_MINOR}" "-Dscala.version=${TRAVIS_SCALA_VERSION}"

    - stage: branchBuild
      name: 'Build Branch'
      install: mvn test -B "-Dscala.artifact.version=${SCALA_MINOR}" "-Dscala.version=${TRAVIS_SCALA_VERSION}"

    - stage: tagDeploy
      name: 'Publish Release'
      install: mvn deploy --settings target/travis/settings.xml "-Dscala.artifact.version=${SCALA_MINOR}" "-Dscala.version=${TRAVIS_SCALA_VERSION}"

    - stage: siteDeploy
      name: 'Deploy Github Site'
      script: mvn site-deploy -P github-site "-Dgithub.global.oauth2Token=${GITHUB_TOKEN}"

    - stage: scoverage
      name: 'Scoverage Report'
      script: mvn scoverage:report

    - stage: coveralls
      name: 'Coveralls Report'
      script: mvn coveralls:report

stages:
  - checkout
  - name: version
    if: tag IS present
  - name: branchBuild
    if: tag IS blank
  - name: tagDeploy
    if: tag IS present
  - name: siteDeploy
    if: tag IS present
  - name: scoverage
    if: type != pull_request AND tag IS blank
  - name: coveralls
    if: type != pull_request